### ISSUE TITLE
Ability to open images in carousel mode or as preview

### ISSUE THREAD

**Issue by jayloofah** [heychirag/jekyll-google-photos#5]
Wondering if it would be possible to implement a preview mode when clicking on the individual photos or an option to treat the album as one single slideshow object as is possible [here](https://www.publicalbum.org/blog/embedding-google-photos-albums)?

**Comment by heychirag** [comment]
Hi @jayloofah 

The primary focus of this plugin is to provide the backend support needed for displaying a Google Photos album on your website. The plugin does provide a way to extract all the links of the images, and you can then use a gallery plugin (or write one of your own) to display images the way you want. The reason for doing so is because there are potentially many ways to implement a gallery, so it was logical to only provide a backend support.

The Best,
Chirag

**Comment by heychirag** [comment]
Hi @jayloofah 

> Wondering if it would be possible to implement a preview mode when clicking on the individual photos or an option to treat the album as one single slideshow object as is possible here?

Yes, of course. Since this plugin provides you with the image URLs, you can easily use it with the carousel you want to. Look at the following example:

```
{% google_photos https://photos.app.goo.gl/bhWukds8QVodFU246 none %}

<script src="https://cdn.jsdelivr.net/npm/publicalbum@latest/embed-ui.min.js" async></script>

<div class="pa-gallery-player-widget" style="width:100%; height:480px; display:none;"
  data-link="<Album link>"
  data-title="<Album Name>"
  data-description="<Album Description>"
  data-delay="5"
  id="MyAlbum1">
</div>

<script>
  let MyAlbum1 = document.getElementById('MyAlbum1');
  let imageWidth = '0';
  for(var i in googlePhotos.urls) {
    let picture = document.createElement('object');
    picture.setAttribute("data", googlePhotos.urls[i] + '=w' + imageWidth);
    MyAlbum1.appendChild(picture);
  }
</script>
```

This generates the same kind of carousel
